model: "HuggingFaceTB/SmolLM2-135M"
train: True
mask_prompt: True
data: "./sentiment"
adapter_path: "./sentiment-adapter"
iters: 2000
batch_size: 4
learning_rate: 1e-4
steps_per_report: 10
val_batches: 50
steps_per_eval: 100
test: True

num_layers: -1
# according to original paper
lora_parameters:
  rank: 16
  dropout: 0.05
  scale: 32.0
  #keys: ["self_attn.q_proj", "self_attn.v_proj"]

